### ISSUE TITLE
Enable Repository Template

### ISSUE THREAD

**Issue by halotroop2288** [SonicEraZoR/Portal-Base#7]
As the title of the repo suggests, this would be an excellent base for other Portal + Source 2013-based mods. If you would enable project templates, it would allow others to create a new repository based on it that is not tracked as a fork.

**Comment by SonicEraZoR** [comment]
Enabled it. Though initially when I created this repo I cloned [https://github.com/ValveSoftware/source-sdk-2013](source-sdk-2013) repo using some guide that used Git's CLI to do that, so that's another option. It also preserves commits history unlike the other option, which is kind of nice I think.
